<?php
ini_set('display_errors', 1);
$sBoardName="Imageboard";
$sPostReply="Post Reply";
$sPost="Post";
$sAnonymous="Anonymous";
$sReplies="replies";
$sDatabaseError="<h1>Error: Database error</h1>";
$sThreadNotFound="<h1>Error: Thread not found</h1>";
$sNameTooLong="<h1>Error: Name is too long</h1>";
$sIllegalPost="<h1>Error: Illegal post</h1>";
$sPostTooLong="<h1>Error: Post is too long</h1>";
$sLockError="<h1>Error: Can't lock database</h1>";
$sBan="<center><h1>Banned</h1><br><img src=\"banned.png\" width=\"400\"></center><br><hr> Reason: ";
$sSilentBan="";
$sCooldown="<h1>Error: You're posting too fast.</h1>";
$sSticky="";
$sCaptchaFail="<h1>Error: Captcha is missing or wrong</h1>";
$sStream="All posts";
$sNormal="Show threads";
$sReport="Report";
$sLegal="All trademarks and copyrights on this page are owned by their respective parties. Images uploaded are the responsibility of the Poster. Comments are owned by the Poster.";
$sWait="Please wait: ";
$sSeconds="s.";

$webmLogo="logo/webm.jpg";
$logo="logo/logo.png";
$database="database/posts.csv";
$bans="database/bans.csv";
$pictures="images/images";
$css="css";
$maxThreads=150;
$maxPostLength=3000;
$maxUpload=4096+2048;
$maxLines=100;
$report="";
$cooldown=60;
$thumbnails="images/thumbnails";
$pro=4;
$proCooldown=10;
$initialCooldown=120;
$key="loh";
$ipsalt="secret";
?>
